/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedTreinamentoIaRouteImport } from './routes/_authenticated/treinamento-ia'
import { Route as AuthenticatedSmsFollowupRouteImport } from './routes/_authenticated/sms-followup'
import { Route as AuthenticatedSmsRouteImport } from './routes/_authenticated/sms'
import { Route as AuthenticatedPersonalidadeIaRouteImport } from './routes/_authenticated/personalidade-ia'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedGuiaRouteImport } from './routes/_authenticated/guia'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated/contratos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCasosRouteImport } from './routes/_authenticated/casos'
import { Route as AuthenticatedBaseConhecimentoRouteImport } from './routes/_authenticated/base-conhecimento'
import { Route as AuthenticatedAgendamentosRouteImport } from './routes/_authenticated/agendamentos'
import { Route as AuthenticatedContratosIndexRouteImport } from './routes/_authenticated/contratos.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicWapiWebhookRouteImport } from './routes/api/public/wapi-webhook'
import { Route as ApiPublicWapiMediaRetryRouteImport } from './routes/api/public/wapi-media-retry'
import { Route as ApiPublicSmsCronRouteImport } from './routes/api/public/sms-cron'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'
import { Route as ApiPublicImportWebhookRouteImport } from './routes/api/public/import-webhook'
import { Route as ApiPublicFollowupCronRouteImport } from './routes/api/public/followup-cron'
import { Route as ApiPublicContractsRemindersCronRouteImport } from './routes/api/public/contracts-reminders-cron'
import { Route as ApiPublicAutentiqueWebhookRouteImport } from './routes/api/public/autentique-webhook'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas-webhook'
import { Route as ApiMediaMediaIdRouteImport } from './routes/api/media/$mediaId'
import { Route as AuthenticatedKanbanConfiguracoesRouteImport } from './routes/_authenticated/kanban.configuracoes'
import { Route as AuthenticatedEduardoContractIdRouteImport } from './routes/_authenticated/eduardo.$contractId'
import { Route as AuthenticatedContratosTemplatesRouteImport } from './routes/_authenticated/contratos.templates'
import { Route as AuthenticatedContratosNovoRouteImport } from './routes/_authenticated/contratos.novo'
import { Route as AuthenticatedContratosIdRouteImport } from './routes/_authenticated/contratos.$id'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminSetoresRouteImport } from './routes/_authenticated/admin.setores'
import { Route as AuthenticatedAdminConvitesRouteImport } from './routes/_authenticated/admin.convites'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicTtsAudioTokenRouteImport } from './routes/api/public/tts/$audioToken'
import { Route as ApiPublicMediaMediaIdRouteImport } from './routes/api/public/media/$mediaId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreinamentoIaRoute =
  AuthenticatedTreinamentoIaRouteImport.update({
    id: '/treinamento-ia',
    path: '/treinamento-ia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSmsFollowupRoute =
  AuthenticatedSmsFollowupRouteImport.update({
    id: '/sms-followup',
    path: '/sms-followup',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSmsRoute = AuthenticatedSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonalidadeIaRoute =
  AuthenticatedPersonalidadeIaRouteImport.update({
    id: '/personalidade-ia',
    path: '/personalidade-ia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuiaRoute = AuthenticatedGuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasosRoute = AuthenticatedCasosRouteImport.update({
  id: '/casos',
  path: '/casos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBaseConhecimentoRoute =
  AuthenticatedBaseConhecimentoRouteImport.update({
    id: '/base-conhecimento',
    path: '/base-conhecimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendamentosRoute =
  AuthenticatedAgendamentosRouteImport.update({
    id: '/agendamentos',
    path: '/agendamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosIndexRoute =
  AuthenticatedContratosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedContratosRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWapiWebhookRoute = ApiPublicWapiWebhookRouteImport.update({
  id: '/api/public/wapi-webhook',
  path: '/api/public/wapi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWapiMediaRetryRoute = ApiPublicWapiMediaRetryRouteImport.update({
  id: '/api/public/wapi-media-retry',
  path: '/api/public/wapi-media-retry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSmsCronRoute = ApiPublicSmsCronRouteImport.update({
  id: '/api/public/sms-cron',
  path: '/api/public/sms-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicImportWebhookRoute = ApiPublicImportWebhookRouteImport.update({
  id: '/api/public/import-webhook',
  path: '/api/public/import-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFollowupCronRoute = ApiPublicFollowupCronRouteImport.update({
  id: '/api/public/followup-cron',
  path: '/api/public/followup-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContractsRemindersCronRoute =
  ApiPublicContractsRemindersCronRouteImport.update({
    id: '/api/public/contracts-reminders-cron',
    path: '/api/public/contracts-reminders-cron',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAutentiqueWebhookRoute =
  ApiPublicAutentiqueWebhookRouteImport.update({
    id: '/api/public/autentique-webhook',
    path: '/api/public/autentique-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaMediaIdRoute = ApiMediaMediaIdRouteImport.update({
  id: '/api/media/$mediaId',
  path: '/api/media/$mediaId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKanbanConfiguracoesRoute =
  AuthenticatedKanbanConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedKanbanRoute,
  } as any)
const AuthenticatedEduardoContractIdRoute =
  AuthenticatedEduardoContractIdRouteImport.update({
    id: '/eduardo/$contractId',
    path: '/eduardo/$contractId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosTemplatesRoute =
  AuthenticatedContratosTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedContratosRoute,
  } as any)
const AuthenticatedContratosNovoRoute =
  AuthenticatedContratosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedContratosRoute,
  } as any)
const AuthenticatedContratosIdRoute =
  AuthenticatedContratosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedContratosRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSetoresRoute =
  AuthenticatedAdminSetoresRouteImport.update({
    id: '/admin/setores',
    path: '/admin/setores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConvitesRoute =
  AuthenticatedAdminConvitesRouteImport.update({
    id: '/admin/convites',
    path: '/admin/convites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTtsAudioTokenRoute = ApiPublicTtsAudioTokenRouteImport.update({
  id: '/api/public/tts/$audioToken',
  path: '/api/public/tts/$audioToken',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaMediaIdRoute = ApiPublicMediaMediaIdRouteImport.update({
  id: '/api/public/media/$mediaId',
  path: '/api/public/media/$mediaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/agendamentos': typeof AuthenticatedAgendamentosRoute
  '/base-conhecimento': typeof AuthenticatedBaseConhecimentoRoute
  '/casos': typeof AuthenticatedCasosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contratos': typeof AuthenticatedContratosRouteWithChildren
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guia': typeof AuthenticatedGuiaRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/kanban': typeof AuthenticatedKanbanRouteWithChildren
  '/personalidade-ia': typeof AuthenticatedPersonalidadeIaRoute
  '/sms': typeof AuthenticatedSmsRoute
  '/sms-followup': typeof AuthenticatedSmsFollowupRoute
  '/treinamento-ia': typeof AuthenticatedTreinamentoIaRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/admin/convites': typeof AuthenticatedAdminConvitesRoute
  '/admin/setores': typeof AuthenticatedAdminSetoresRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/contratos/novo': typeof AuthenticatedContratosNovoRoute
  '/contratos/templates': typeof AuthenticatedContratosTemplatesRoute
  '/eduardo/$contractId': typeof AuthenticatedEduardoContractIdRoute
  '/kanban/configuracoes': typeof AuthenticatedKanbanConfiguracoesRoute
  '/api/media/$mediaId': typeof ApiMediaMediaIdRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/autentique-webhook': typeof ApiPublicAutentiqueWebhookRoute
  '/api/public/contracts-reminders-cron': typeof ApiPublicContractsRemindersCronRoute
  '/api/public/followup-cron': typeof ApiPublicFollowupCronRoute
  '/api/public/import-webhook': typeof ApiPublicImportWebhookRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/sms-cron': typeof ApiPublicSmsCronRoute
  '/api/public/wapi-media-retry': typeof ApiPublicWapiMediaRetryRoute
  '/api/public/wapi-webhook': typeof ApiPublicWapiWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/contratos/': typeof AuthenticatedContratosIndexRoute
  '/api/public/media/$mediaId': typeof ApiPublicMediaMediaIdRoute
  '/api/public/tts/$audioToken': typeof ApiPublicTtsAudioTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/agendamentos': typeof AuthenticatedAgendamentosRoute
  '/base-conhecimento': typeof AuthenticatedBaseConhecimentoRoute
  '/casos': typeof AuthenticatedCasosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guia': typeof AuthenticatedGuiaRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/kanban': typeof AuthenticatedKanbanRouteWithChildren
  '/personalidade-ia': typeof AuthenticatedPersonalidadeIaRoute
  '/sms': typeof AuthenticatedSmsRoute
  '/sms-followup': typeof AuthenticatedSmsFollowupRoute
  '/treinamento-ia': typeof AuthenticatedTreinamentoIaRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/admin/convites': typeof AuthenticatedAdminConvitesRoute
  '/admin/setores': typeof AuthenticatedAdminSetoresRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/contratos/novo': typeof AuthenticatedContratosNovoRoute
  '/contratos/templates': typeof AuthenticatedContratosTemplatesRoute
  '/eduardo/$contractId': typeof AuthenticatedEduardoContractIdRoute
  '/kanban/configuracoes': typeof AuthenticatedKanbanConfiguracoesRoute
  '/api/media/$mediaId': typeof ApiMediaMediaIdRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/autentique-webhook': typeof ApiPublicAutentiqueWebhookRoute
  '/api/public/contracts-reminders-cron': typeof ApiPublicContractsRemindersCronRoute
  '/api/public/followup-cron': typeof ApiPublicFollowupCronRoute
  '/api/public/import-webhook': typeof ApiPublicImportWebhookRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/sms-cron': typeof ApiPublicSmsCronRoute
  '/api/public/wapi-media-retry': typeof ApiPublicWapiMediaRetryRoute
  '/api/public/wapi-webhook': typeof ApiPublicWapiWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/contratos': typeof AuthenticatedContratosIndexRoute
  '/api/public/media/$mediaId': typeof ApiPublicMediaMediaIdRoute
  '/api/public/tts/$audioToken': typeof ApiPublicTtsAudioTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/agendamentos': typeof AuthenticatedAgendamentosRoute
  '/_authenticated/base-conhecimento': typeof AuthenticatedBaseConhecimentoRoute
  '/_authenticated/casos': typeof AuthenticatedCasosRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRouteWithChildren
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/guia': typeof AuthenticatedGuiaRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRouteWithChildren
  '/_authenticated/personalidade-ia': typeof AuthenticatedPersonalidadeIaRoute
  '/_authenticated/sms': typeof AuthenticatedSmsRoute
  '/_authenticated/sms-followup': typeof AuthenticatedSmsFollowupRoute
  '/_authenticated/treinamento-ia': typeof AuthenticatedTreinamentoIaRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/_authenticated/admin/convites': typeof AuthenticatedAdminConvitesRoute
  '/_authenticated/admin/setores': typeof AuthenticatedAdminSetoresRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/_authenticated/contratos/novo': typeof AuthenticatedContratosNovoRoute
  '/_authenticated/contratos/templates': typeof AuthenticatedContratosTemplatesRoute
  '/_authenticated/eduardo/$contractId': typeof AuthenticatedEduardoContractIdRoute
  '/_authenticated/kanban/configuracoes': typeof AuthenticatedKanbanConfiguracoesRoute
  '/api/media/$mediaId': typeof ApiMediaMediaIdRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/autentique-webhook': typeof ApiPublicAutentiqueWebhookRoute
  '/api/public/contracts-reminders-cron': typeof ApiPublicContractsRemindersCronRoute
  '/api/public/followup-cron': typeof ApiPublicFollowupCronRoute
  '/api/public/import-webhook': typeof ApiPublicImportWebhookRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/sms-cron': typeof ApiPublicSmsCronRoute
  '/api/public/wapi-media-retry': typeof ApiPublicWapiMediaRetryRoute
  '/api/public/wapi-webhook': typeof ApiPublicWapiWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/contratos/': typeof AuthenticatedContratosIndexRoute
  '/api/public/media/$mediaId': typeof ApiPublicMediaMediaIdRoute
  '/api/public/tts/$audioToken': typeof ApiPublicTtsAudioTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agendamentos'
    | '/base-conhecimento'
    | '/casos'
    | '/clientes'
    | '/configuracoes'
    | '/contratos'
    | '/crm'
    | '/dashboard'
    | '/guia'
    | '/integracoes'
    | '/kanban'
    | '/personalidade-ia'
    | '/sms'
    | '/sms-followup'
    | '/treinamento-ia'
    | '/whatsapp'
    | '/auth/callback'
    | '/convite/$token'
    | '/admin/convites'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/contratos/$id'
    | '/contratos/novo'
    | '/contratos/templates'
    | '/eduardo/$contractId'
    | '/kanban/configuracoes'
    | '/api/media/$mediaId'
    | '/api/public/asaas-webhook'
    | '/api/public/autentique-webhook'
    | '/api/public/contracts-reminders-cron'
    | '/api/public/followup-cron'
    | '/api/public/import-webhook'
    | '/api/public/mercadopago-webhook'
    | '/api/public/sms-cron'
    | '/api/public/wapi-media-retry'
    | '/api/public/wapi-webhook'
    | '/admin/'
    | '/contratos/'
    | '/api/public/media/$mediaId'
    | '/api/public/tts/$audioToken'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agendamentos'
    | '/base-conhecimento'
    | '/casos'
    | '/clientes'
    | '/configuracoes'
    | '/crm'
    | '/dashboard'
    | '/guia'
    | '/integracoes'
    | '/kanban'
    | '/personalidade-ia'
    | '/sms'
    | '/sms-followup'
    | '/treinamento-ia'
    | '/whatsapp'
    | '/auth/callback'
    | '/convite/$token'
    | '/admin/convites'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/contratos/$id'
    | '/contratos/novo'
    | '/contratos/templates'
    | '/eduardo/$contractId'
    | '/kanban/configuracoes'
    | '/api/media/$mediaId'
    | '/api/public/asaas-webhook'
    | '/api/public/autentique-webhook'
    | '/api/public/contracts-reminders-cron'
    | '/api/public/followup-cron'
    | '/api/public/import-webhook'
    | '/api/public/mercadopago-webhook'
    | '/api/public/sms-cron'
    | '/api/public/wapi-media-retry'
    | '/api/public/wapi-webhook'
    | '/admin'
    | '/contratos'
    | '/api/public/media/$mediaId'
    | '/api/public/tts/$audioToken'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agendamentos'
    | '/_authenticated/base-conhecimento'
    | '/_authenticated/casos'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contratos'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/guia'
    | '/_authenticated/integracoes'
    | '/_authenticated/kanban'
    | '/_authenticated/personalidade-ia'
    | '/_authenticated/sms'
    | '/_authenticated/sms-followup'
    | '/_authenticated/treinamento-ia'
    | '/_authenticated/whatsapp'
    | '/auth/callback'
    | '/convite/$token'
    | '/_authenticated/admin/convites'
    | '/_authenticated/admin/setores'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/contratos/$id'
    | '/_authenticated/contratos/novo'
    | '/_authenticated/contratos/templates'
    | '/_authenticated/eduardo/$contractId'
    | '/_authenticated/kanban/configuracoes'
    | '/api/media/$mediaId'
    | '/api/public/asaas-webhook'
    | '/api/public/autentique-webhook'
    | '/api/public/contracts-reminders-cron'
    | '/api/public/followup-cron'
    | '/api/public/import-webhook'
    | '/api/public/mercadopago-webhook'
    | '/api/public/sms-cron'
    | '/api/public/wapi-media-retry'
    | '/api/public/wapi-webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/contratos/'
    | '/api/public/media/$mediaId'
    | '/api/public/tts/$audioToken'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ConviteTokenRoute: typeof ConviteTokenRoute
  ApiMediaMediaIdRoute: typeof ApiMediaMediaIdRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
  ApiPublicAutentiqueWebhookRoute: typeof ApiPublicAutentiqueWebhookRoute
  ApiPublicContractsRemindersCronRoute: typeof ApiPublicContractsRemindersCronRoute
  ApiPublicFollowupCronRoute: typeof ApiPublicFollowupCronRoute
  ApiPublicImportWebhookRoute: typeof ApiPublicImportWebhookRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
  ApiPublicSmsCronRoute: typeof ApiPublicSmsCronRoute
  ApiPublicWapiMediaRetryRoute: typeof ApiPublicWapiMediaRetryRoute
  ApiPublicWapiWebhookRoute: typeof ApiPublicWapiWebhookRoute
  ApiPublicMediaMediaIdRoute: typeof ApiPublicMediaMediaIdRoute
  ApiPublicTtsAudioTokenRoute: typeof ApiPublicTtsAudioTokenRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinamento-ia': {
      id: '/_authenticated/treinamento-ia'
      path: '/treinamento-ia'
      fullPath: '/treinamento-ia'
      preLoaderRoute: typeof AuthenticatedTreinamentoIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sms-followup': {
      id: '/_authenticated/sms-followup'
      path: '/sms-followup'
      fullPath: '/sms-followup'
      preLoaderRoute: typeof AuthenticatedSmsFollowupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sms': {
      id: '/_authenticated/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof AuthenticatedSmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personalidade-ia': {
      id: '/_authenticated/personalidade-ia'
      path: '/personalidade-ia'
      fullPath: '/personalidade-ia'
      preLoaderRoute: typeof AuthenticatedPersonalidadeIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guia': {
      id: '/_authenticated/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof AuthenticatedGuiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/casos': {
      id: '/_authenticated/casos'
      path: '/casos'
      fullPath: '/casos'
      preLoaderRoute: typeof AuthenticatedCasosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/base-conhecimento': {
      id: '/_authenticated/base-conhecimento'
      path: '/base-conhecimento'
      fullPath: '/base-conhecimento'
      preLoaderRoute: typeof AuthenticatedBaseConhecimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agendamentos': {
      id: '/_authenticated/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AuthenticatedAgendamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/': {
      id: '/_authenticated/contratos/'
      path: '/'
      fullPath: '/contratos/'
      preLoaderRoute: typeof AuthenticatedContratosIndexRouteImport
      parentRoute: typeof AuthenticatedContratosRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/wapi-webhook': {
      id: '/api/public/wapi-webhook'
      path: '/api/public/wapi-webhook'
      fullPath: '/api/public/wapi-webhook'
      preLoaderRoute: typeof ApiPublicWapiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wapi-media-retry': {
      id: '/api/public/wapi-media-retry'
      path: '/api/public/wapi-media-retry'
      fullPath: '/api/public/wapi-media-retry'
      preLoaderRoute: typeof ApiPublicWapiMediaRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sms-cron': {
      id: '/api/public/sms-cron'
      path: '/api/public/sms-cron'
      fullPath: '/api/public/sms-cron'
      preLoaderRoute: typeof ApiPublicSmsCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/import-webhook': {
      id: '/api/public/import-webhook'
      path: '/api/public/import-webhook'
      fullPath: '/api/public/import-webhook'
      preLoaderRoute: typeof ApiPublicImportWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/followup-cron': {
      id: '/api/public/followup-cron'
      path: '/api/public/followup-cron'
      fullPath: '/api/public/followup-cron'
      preLoaderRoute: typeof ApiPublicFollowupCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contracts-reminders-cron': {
      id: '/api/public/contracts-reminders-cron'
      path: '/api/public/contracts-reminders-cron'
      fullPath: '/api/public/contracts-reminders-cron'
      preLoaderRoute: typeof ApiPublicContractsRemindersCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/autentique-webhook': {
      id: '/api/public/autentique-webhook'
      path: '/api/public/autentique-webhook'
      fullPath: '/api/public/autentique-webhook'
      preLoaderRoute: typeof ApiPublicAutentiqueWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$mediaId': {
      id: '/api/media/$mediaId'
      path: '/api/media/$mediaId'
      fullPath: '/api/media/$mediaId'
      preLoaderRoute: typeof ApiMediaMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/kanban/configuracoes': {
      id: '/_authenticated/kanban/configuracoes'
      path: '/configuracoes'
      fullPath: '/kanban/configuracoes'
      preLoaderRoute: typeof AuthenticatedKanbanConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedKanbanRoute
    }
    '/_authenticated/eduardo/$contractId': {
      id: '/_authenticated/eduardo/$contractId'
      path: '/eduardo/$contractId'
      fullPath: '/eduardo/$contractId'
      preLoaderRoute: typeof AuthenticatedEduardoContractIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos/templates': {
      id: '/_authenticated/contratos/templates'
      path: '/templates'
      fullPath: '/contratos/templates'
      preLoaderRoute: typeof AuthenticatedContratosTemplatesRouteImport
      parentRoute: typeof AuthenticatedContratosRoute
    }
    '/_authenticated/contratos/novo': {
      id: '/_authenticated/contratos/novo'
      path: '/novo'
      fullPath: '/contratos/novo'
      preLoaderRoute: typeof AuthenticatedContratosNovoRouteImport
      parentRoute: typeof AuthenticatedContratosRoute
    }
    '/_authenticated/contratos/$id': {
      id: '/_authenticated/contratos/$id'
      path: '/$id'
      fullPath: '/contratos/$id'
      preLoaderRoute: typeof AuthenticatedContratosIdRouteImport
      parentRoute: typeof AuthenticatedContratosRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/setores': {
      id: '/_authenticated/admin/setores'
      path: '/admin/setores'
      fullPath: '/admin/setores'
      preLoaderRoute: typeof AuthenticatedAdminSetoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/convites': {
      id: '/_authenticated/admin/convites'
      path: '/admin/convites'
      fullPath: '/admin/convites'
      preLoaderRoute: typeof AuthenticatedAdminConvitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tts/$audioToken': {
      id: '/api/public/tts/$audioToken'
      path: '/api/public/tts/$audioToken'
      fullPath: '/api/public/tts/$audioToken'
      preLoaderRoute: typeof ApiPublicTtsAudioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$mediaId': {
      id: '/api/public/media/$mediaId'
      path: '/api/public/media/$mediaId'
      fullPath: '/api/public/media/$mediaId'
      preLoaderRoute: typeof ApiPublicMediaMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedContratosRouteChildren {
  AuthenticatedContratosIdRoute: typeof AuthenticatedContratosIdRoute
  AuthenticatedContratosNovoRoute: typeof AuthenticatedContratosNovoRoute
  AuthenticatedContratosTemplatesRoute: typeof AuthenticatedContratosTemplatesRoute
  AuthenticatedContratosIndexRoute: typeof AuthenticatedContratosIndexRoute
}

const AuthenticatedContratosRouteChildren: AuthenticatedContratosRouteChildren =
  {
    AuthenticatedContratosIdRoute: AuthenticatedContratosIdRoute,
    AuthenticatedContratosNovoRoute: AuthenticatedContratosNovoRoute,
    AuthenticatedContratosTemplatesRoute: AuthenticatedContratosTemplatesRoute,
    AuthenticatedContratosIndexRoute: AuthenticatedContratosIndexRoute,
  }

const AuthenticatedContratosRouteWithChildren =
  AuthenticatedContratosRoute._addFileChildren(
    AuthenticatedContratosRouteChildren,
  )

interface AuthenticatedKanbanRouteChildren {
  AuthenticatedKanbanConfiguracoesRoute: typeof AuthenticatedKanbanConfiguracoesRoute
}

const AuthenticatedKanbanRouteChildren: AuthenticatedKanbanRouteChildren = {
  AuthenticatedKanbanConfiguracoesRoute: AuthenticatedKanbanConfiguracoesRoute,
}

const AuthenticatedKanbanRouteWithChildren =
  AuthenticatedKanbanRoute._addFileChildren(AuthenticatedKanbanRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendamentosRoute: typeof AuthenticatedAgendamentosRoute
  AuthenticatedBaseConhecimentoRoute: typeof AuthenticatedBaseConhecimentoRoute
  AuthenticatedCasosRoute: typeof AuthenticatedCasosRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRouteWithChildren
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGuiaRoute: typeof AuthenticatedGuiaRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRouteWithChildren
  AuthenticatedPersonalidadeIaRoute: typeof AuthenticatedPersonalidadeIaRoute
  AuthenticatedSmsRoute: typeof AuthenticatedSmsRoute
  AuthenticatedSmsFollowupRoute: typeof AuthenticatedSmsFollowupRoute
  AuthenticatedTreinamentoIaRoute: typeof AuthenticatedTreinamentoIaRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedAdminConvitesRoute: typeof AuthenticatedAdminConvitesRoute
  AuthenticatedAdminSetoresRoute: typeof AuthenticatedAdminSetoresRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedEduardoContractIdRoute: typeof AuthenticatedEduardoContractIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendamentosRoute: AuthenticatedAgendamentosRoute,
  AuthenticatedBaseConhecimentoRoute: AuthenticatedBaseConhecimentoRoute,
  AuthenticatedCasosRoute: AuthenticatedCasosRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContratosRoute: AuthenticatedContratosRouteWithChildren,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGuiaRoute: AuthenticatedGuiaRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRouteWithChildren,
  AuthenticatedPersonalidadeIaRoute: AuthenticatedPersonalidadeIaRoute,
  AuthenticatedSmsRoute: AuthenticatedSmsRoute,
  AuthenticatedSmsFollowupRoute: AuthenticatedSmsFollowupRoute,
  AuthenticatedTreinamentoIaRoute: AuthenticatedTreinamentoIaRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedAdminConvitesRoute: AuthenticatedAdminConvitesRoute,
  AuthenticatedAdminSetoresRoute: AuthenticatedAdminSetoresRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedEduardoContractIdRoute: AuthenticatedEduardoContractIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ConviteTokenRoute: ConviteTokenRoute,
  ApiMediaMediaIdRoute: ApiMediaMediaIdRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
  ApiPublicAutentiqueWebhookRoute: ApiPublicAutentiqueWebhookRoute,
  ApiPublicContractsRemindersCronRoute: ApiPublicContractsRemindersCronRoute,
  ApiPublicFollowupCronRoute: ApiPublicFollowupCronRoute,
  ApiPublicImportWebhookRoute: ApiPublicImportWebhookRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
  ApiPublicSmsCronRoute: ApiPublicSmsCronRoute,
  ApiPublicWapiMediaRetryRoute: ApiPublicWapiMediaRetryRoute,
  ApiPublicWapiWebhookRoute: ApiPublicWapiWebhookRoute,
  ApiPublicMediaMediaIdRoute: ApiPublicMediaMediaIdRoute,
  ApiPublicTtsAudioTokenRoute: ApiPublicTtsAudioTokenRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
